### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by joshuaulrich** [R-Finance/rfinance#6]
The [About page](https://github.com/R-Finance/rfinance/blob/master/content/about.md) needs some attention.  It's currently a draft from @jaryan's prototype site.

**Comment by JustinMShea** [comment]
I've begun reworking @jaryan 's about draft. There are still some redundancies to eliminate from moving content around, punctuation to edit, and general content to clarify. 

One question I have is regarding the number of packages / collaborations that have come out of R Finance. Jeff acknowledges this in several sections and I think its valuable content as its truly reflective of what happens here. Should we consider a separate page for this altogether, or just clean up the list and keep it one section, such as R code?

**Comment by JustinMShea** [comment]
Major update pushed last week.
